name: Deploy to VPS with Docker and Git Actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sinkronisasi file dari S3 ke direktori lokal di VPS
        run: |
          aws s3 sync s3://docker-actions /var/www/html/assets_nginx1 --delete
          aws s3 sync s3://docker-actions /var/www/html/assets_nginx2 --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-2

      - name: Start Nginx Container 1
        run: |
          sudo docker run -d -p 8080:80 --name nginx-container1 --network bridge -v /var/www/html/assets_nginx1:/usr/share/nginx/html:ro nginx

      - name: Start Nginx Container 2
        run: |
          sudo docker run -d -p 8081:80 --name nginx-container2 --network bridge -v /var/www/html/assets_nginx2:/usr/share/nginx/html:ro nginx
