### Git Self Hosted ###
name: Deploy to VPS with Docker Compose and Git Actions

on:
  repository_dispatch:
    types: [start-deploy]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync files from S3 to local VPS directory
        run: |
          mkdir -p /var/www/html/assets_nginx1
          aws s3 sync s3://docker-actions/assets /var/www/html/assets_nginx1 --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-2

      - name: Start Docker Compose
        run: |
          sudo docker-compose up -d

      - name: Backup Docker Volume to S3
        run: |
          # Archive the Docker volume data (assumed volume name: `my_volume`)
          docker run --rm -v my_volume:/volume -v /tmp:/backup alpine \
            sh -c "cd /volume && tar -czf /backup/my_volume_backup.tar.gz ."
          
          # Upload backup to S3
          aws s3 cp /tmp/my_volume_backup.tar.gz s3://docker-actions/backups/my_volume_backup_$(date +%F).tar.gz
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-2
