name: Deploy to VPS with Docker and Git Actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sinkronisasi file dari S3 ke direktori lokal di VPS
        run: |
          mkdir -p /var/www/html/assets
          aws s3 sync s3://docker-actions /var/www/html/assets --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: your-region

      - name: Start Nginx Container 1
        run: |
          sudo docker run -d --name nginx-container1 -p 8080:80 -v /var/www/html/assets:/usr/share/nginx/html:ro nginx

      - name: Start Nginx Container 2
        run: |
          sudo docker run -d --name nginx-container2 -p 8081:80 -v /var/www/html/assets:/usr/share/nginx/html:ro nginx
